version: '3.8'

services:
  nginx:
    build:
      context:
        ./docker/nginx
    volumes:
      - ./public:/app/public
      - ./storage:/app/storage
      - ./docker/nginx/cert:/etc/nginx/conf.d/cert
    ports:
      - ${NGINX_PORT}:80
      - 443:443
    networks:
      - default

  php:
    build:
      context:
        ./docker/php
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    volumes:
      - .:/app
    networks:
      - default
    links:
      - mysql
    environment:
      - COMPOSER_MEMORY_LIMIT=-1

  mysql:
    build:
      context:
        ./docker/mysql_8
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}

    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/mysql_8/db:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - default

#
#  mysql_old:
#    build:
#      context:
#        ./docker/mysql
#    volumes:
#      - ./docker/mysql/db:/var/lib/mysql
#    ports:
#      - 4444:3306
#    environment:
#      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#      MYSQL_DATABASE: ${MYSQL_DATABASE}
#      MYSQL_USER: ${MYSQL_USER}
#      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
#    networks:
#      - default

  nodejs:
    build:
      context:
        ./docker/nodejs
    volumes:
      - .:/app
    tty: true


