version: '3.8'

services:
  nginx:
    build:
      context:
        ./docker/nginx
    volumes:
      - ./public:/app/public
      - ./storage:/app/storage
      - ./docker/nginx/cert:/etc/nginx/conf.d/cert
    ports:
      - ${NGINX_PORT:?80}:80
      - ${NGINX_HTTPS_PORT:?443}:443
    networks:
      - landing

  php:
    build:
      context:
        ./docker/php
      args:
        USER_ID: ${USER_ID:?err}
        GROUP_ID: ${GROUP_ID:?err}
    volumes:
      - .:/app
    networks:
      - landing
    links:
      - mysql
    environment:
      - COMPOSER_MEMORY_LIMIT=-1

  mysql:
    build:
      context:
        ./docker/mysql_8

    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/mysql_8/db:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - landing
  nodejs:
    build:
      context:
        ./docker/nodejs
    volumes:
      - .:/app
    tty: true
    networks:
      - landing

networks:
  landing:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"


