# Specifies where to get the base image (Node v12 in our case) and creates a new container for it
FROM node:10

#RUN npm install -g gulp
#RUN npm install -g grunt-cli

#RUN mkdir -p /var/www
#VOLUME ["/var/www"]
#
#WORKDIR /var/www

WORKDIR /app
